version: '2'
services:
    mysql:
        restart: always
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=reviewboard
            - MYSQL_DATABASE=reviewboard
            - MYSQL_USER=reviewboard_dbuser
            - MYSQL_PASSWORD=reviewboard
        volumes: 
            - db_data=/var/lib/mysql
    memcached:
        image: memcached:alpine
    reviewboard:
        build: ./
        volumes: 
            - rb_data=/var/www
        depends_on:
            - mysql
            - memcached
        environment:
            - DBHOST=mysql
            - DBUSER=reviewboard_dbuser
            - DBPASSWORD=reviewboard
            - MEMCACHED=memcached:11211
        ports:
            - 80:80
volumes: 
  db_data:
  rb_data: